#!/bin/bash

# Script to add Supabase Swift package to Xcode project
# This script provides instructions since SPM packages must be added through Xcode UI

echo "============================================"
echo "📦 Adding Supabase Swift Package to Xcode"
echo "============================================"
echo ""
echo "Since Swift Package Manager packages must be added through Xcode's UI,"
echo "please follow these steps:"
echo ""
echo "STEP 1: Open Xcode"
echo "  → Open LTMS.xcodeproj in Xcode"
echo ""
echo "STEP 2: Select Project"
echo "  → Click on 'LTMS' in the Project Navigator (top-left)"
echo "  → Make sure you select the PROJECT (blue icon), not the target"
echo ""
echo "STEP 3: Go to Package Dependencies"
echo "  → Click on the 'Package Dependencies' tab at the top"
echo ""
echo "STEP 4: Add Supabase Package"
echo "  → Click the '+' button at the bottom-left"
echo "  → In the search field, paste this URL:"
echo ""
echo "     https://github.com/supabase/supabase-swift"
echo ""
echo "  → Press Enter/Return"
echo "  → Wait for Xcode to fetch the package info"
echo ""
echo "STEP 5: Select Package Products"
echo "  → In the 'Add to Target' section, select these products:"
echo "     ✅ Supabase"
echo "     ✅ Auth"
echo "     ✅ PostgREST"
echo "     ✅ Realtime (optional)"
echo "     ✅ Storage (optional)"
echo ""
echo "STEP 6: Add Package"
echo "  → Click 'Add Package' button"
echo "  → Wait for Xcode to download and integrate the package"
echo ""
echo "STEP 7: Verify Installation"
echo "  → Build the project (Cmd+B)"
echo "  → You should see 'Build Succeeded'"
echo ""
echo "============================================"
echo "✅ Once completed, the Supabase SDK will be ready!"
echo "============================================"
echo ""
echo "Next steps after adding the package:"
echo "1. Update Supabase-Info.plist with your credentials"
echo "2. Add the new Swift files to your Xcode project"
echo "3. Build and test the app"
echo ""
